### ISSUE TITLE
Add Macro as Data Type

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/worldbuilding#29]
In GitLab by @brunocalado on Dec 7, 2020, 18:46

Hi.

If you create a new data type called macro and let the user add a macro to it that execute on item click there will be great benefits.

You could create itens with all automation you want. 

Example: You could create moves for Apocalypse World that on click will read the attribute and tell the result. 

I did something similiar to a kult macro ([link](https://raw.githubusercontent.com/brunocalado/mestre-digital/master/Foundry%20VTT/Macros/Kult/KultMoves.js)). 

![image](http://gitlab.com/foundrynet/worldbuilding/uploads/e094451d7671e9048ae2c13e7dd00ea2/image.png)

**Comment by brunocalado** [comment]
nice
