### ISSUE TITLE
Add support for item groups on character sheets.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/worldbuilding#30]
In GitLab by @Asacolips on Dec 8, 2020, 10:18

Similar to the recent attribute group feature for the attributes tab, it would helpful for organization purposes if the items tab of character sheets supported custom groups to be defined for items.

**Comment by TheMathKing** [comment]
Hi, 

Has anyone figured out how to add an item folder in the token item tab?

Thanks!
