### ISSUE TITLE
Fatal error with _applyItemsFormulaReplacements()

### ISSUE THREAD

**Issue by asacolips** [foundryvtt/worldbuilding#53]
From [CrenshawJS in Discord](https://discord.com/channels/170995199584108546/1037073983335563457/1043702538039459880):

## Summary

Players are unable to use chat macros due to a fatal error in `_applyItemsFormulaReplacements()`

## Version Information

- Windows 10
- Hosted with Forge
- No modules enabled
- Foundry version: **v10.290**
- SWB version: **0.7.2**
- Players have all permissions

## Steps to reproduce

Create the following macro (global, chat, no triggers set)

```
/r 1d6cs>=5 # Disadvantage
```

This runs successfully for GM users, but causes an error for players.

## Error Message

[Screenshot of error](https://cdn.discordapp.com/attachments/1037073983335563457/1043702594998116435/Foundry-Errors-Chat-Macros.jpg)

```
Error Msg: There was an error in your chat message syntax.

foundry.js:747 TypeError: data.items[item][k].replace is not a function
[Detected 1 package: system:worldbuilding]
    at SimpleActor._applyItemsFormulaReplacements (actor.js:185)
    at SimpleActor.getRollData (actor.js:54)
    at ChatLog._processDiceCommand (foundry.js:74149)
    at ChatLog.processMessage (foundry.js:74120)
    at Macro._executeChat (foundry.js:19969)
    at Macro.execute (foundry.js:19955)
    at Hotbar._onClickMacro (foundry.js:68047)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.y.handle (jquery.min.js:2)
onError    @    foundry.js:747
    call_wrapped    @    libWrapper-wrapper.js:507
    Hooks.onError#lib-wrapper    @    listeners.js:137
    Hooks.onError#0    @    libWrapper-wrapper.js:187
(anonymous)    @    foundry.js:19970
Promise.catch (async)
_executeChat    @    foundry.js:19969
execute    @    foundry.js:19955
_onClickMacro    @    foundry.js:68047
dispatch    @    jquery.min.js:2
y.handle    @    jquery.min.js:2
When using the chat window, nothing happens.
Error:
actor.js:185 Uncaught (in promise) TypeError: data.items[item][k].replace is not a function
[Detected 1 package: system:worldbuilding]
    at SimpleActor._applyItemsFormulaReplacements (actor.js:185)
    at SimpleActor.getRollData (actor.js:54)
    at ChatMessage.getRollData (foundry.js:18006)
    at ChatMessage.getHTML (foundry.js:18048)
    at ChatLog.postOne (foundry.js:73934)
    at ChatMessage._onCreate (foundry.js:18174)
    at ClientDatabaseBackend.callback (foundry.js:12575)
    at foundry.js:12525
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:12525)
    at ClientDatabaseBackend._createDocuments (foundry.js:12433)
    at async Function.createDocuments (commons.js:6103)
    at async Function.create (commons.js:6226)
```

**Comment by Fyorl** [comment]
There's clearly libWrapper in that stack trace so I'm not sure the claims about 'no modules enabled' can be believed. The 'no triggers set' part is also suspicious. But maybe those are related to it being hosted on the forge? Not ruling out a SWS issue here, but I cannot reproduce it, it might require some particular actor/item setup that has not been included as part of the repro steps.

**Comment by MortiJS** [comment]
Hello.
The problems remain with or without modules. I made a small movie to show the details. First I use a macro as GM/Admin, then as a Trusted Player with all permissions. 
https://drive.google.com/file/d/10OFL8NxdlmXhFhkZvM0R8rymarDRL2Gp/view?usp=sharing

**Comment by Fyorl** [comment]
Thank you for the video. Unfortunately, as I mentioned in my previous comment, following the (very limited) reproduction steps, I am not able to reproduce this. I have attached my own video of following the same steps with no error.

https://user-images.githubusercontent.com/207433/203999706-052a5783-3162-4670-9aff-c4ed7a66c74a.mp4

There is obviously some amount of actor/item setup required to cause this error, but that information has not been provided. I will attempt to work backwards from the stack trace to understand the actor/item state that could cause this, but if you are able to export a world or scene or actor that exhibits this issue reliably, it would help speed up the process.

**Comment by cswendrowski** [comment]
Also was unable to reproduce - 
![image](https://user-images.githubusercontent.com/15639841/204655007-cc32b64a-bc9d-4f50-8820-d3af4616104b.png)

**Comment by MortiJS** [comment]
Thanks a lot for your efforts. I "solved" the problem: If a player ist linked to a character, the player cannot use macros or the chat functions. If I delete this link between player and his character, everything works fine.
