### ISSUE TITLE
Not able to call an attribute inside an attribute group (maybe related to ¤46)

### ISSUE THREAD

**Issue by Battenhatch** [foundryvtt/worldbuilding#55]
I'm experiencing the behaviour that when an attribute is created within an attribute group, I am unable to call it for use in a formula, ie. "1d10 + @Dex" for initiative does not work if Dex is placed in an attribute group.

**Comment by Fyorl** [comment]
Could you elaborate on this? Attributes in groups should appear under their group name. So an attribute called `dex` in a group called `group` should appear under `@group.dex` in the roll data. Is the claim that this behaviour has changed and that attributes used to appear outside of their groups?

**Comment by Battenhatch** [comment]
Ah, so the putting the value in a group changes the "global" name - you are simply not able to call eg. @dex if it's in a group, even if there is no other attribute called dex anywhere. Thanks.
